apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  annotations:
    iam.gke.io/gcp-service-account: "{{ .Values.serviceAccountName }}@{{ .Values.gcpProject }}.iam.gserviceaccount.com"
